### ISSUE TITLE
Doesn't Update resolv.conf on Gentoo

### ISSUE THREAD

**Issue by krafi99** [alfredopalhares/openvpn-update-resolv-conf#34]
I'm trying to use Protonvpn with Openvpn with this script. I have openresolv installed and edited the .ovpn file as per the instructions said here and all other things. But still it's not changing resolv.conf with protonvpn's dns server. I am on Gentoo stable.

**Comment by alfredopalhares** [comment]
Hello, can you show any logs of the client ?

**Comment by krafi99** [comment]
Do you need logs from `sudo openvpn <client-config>.ovpn`?

**Comment by alfredopalhares** [comment]
Yes, increase you verbosity level and omit any sensitive data

**Comment by krafi99** [comment]
Actually, i had unbound and I quite forgot that.
